# configs/phl_geoconv_regression.yaml
task: validate        # "train", "validate", "explain", etc.

experiment_name: "ke_bf_10samps_v1"
output_dir: "/data/hbaier/new_data/geomasking/ke/artifacts/"

dataset:
  type: json                   # maps to JSONGeoAdapter via DatasetRegistry
  data_root: "/data/hbaier/new_data/geomasking/ke/imagery_10samps/"
  prefix: "ke_wi"
  img_size: [256, 256]
  num_workers: 0
  seed: 1337
  temporal: False
  
model:
  name: biasField                # maps to GeoConvNativeRegressor via ModelRegistry

validator:
  device: "cuda"