# configs/phl_geoconv_regression.yaml

task: train        # "train", "validate", "explain", etc.

experiment_name: "ng_swin_10samps_v1"
output_dir: "/data/hbaier/new_data/geomasking/ng/artifacts/"

dataset:
  type: json                   # maps to JSONGeoAdapter via DatasetRegistry
  data_root: "/data/hbaier/new_data/geomasking/ng/imagery_10samps/"
  prefix: "ng2016"
  batch_size: 64
  img_size: [256, 256]
  num_workers: 0
  seed: 1337
  temporal: False
  write_files: True
  
model:
  name: swin                # maps to GeoConvNativeRegressor via ModelRegistry
  # params:
  #   weights: "IMAGENET1K_V1"

trainer:
  epochs: 200
  lr: .00001
  device: "cuda"
  # save_every: 1
  eval_every: 1
  early_stop: null             # or {patience: 3, metric: "val_rmse"}
